import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generatePDF = async (data, elementId = 'analysis-report') => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Helper for text
  const addHeader = (pageNum) => {
    doc.setFillColor(10, 14, 26);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(0, 212, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text('MediLens AI', 20, 25);
    doc.setFontSize(10);
    doc.text('See Beyond the Prescription', 20, 32);
    
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${pageNum}`, pageWidth - 30, 25);
    
    // Bottom border
    doc.setDrawColor(255, 255, 255, 0.1);
    doc.line(0, 40, pageWidth, 40);
  };

  const addFooter = () => {
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by MediLens AI | For informational purposes only | Consult your doctor', pageWidth / 2, pageHeight - 10, { align: 'center' });
    
    // Watermark
    doc.saveGraphicsState();
    doc.setGState(new doc.GState({ opacity: 0.05 }));
    doc.setFontSize(100);
    doc.setTextColor(0, 212, 255);
    doc.text('MediLens AI', pageWidth / 2, pageHeight / 2, { angle: 45, align: 'center' });
    doc.restoreGraphicsState();
  };

  // Page 1: Info
  addHeader(1);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text('Medical Prescription Analysis Report', 20, 55);
  doc.setFontSize(10);
  doc.text(`Date: ${new Date().toLocaleString()}`, 20, 62);

  doc.setDrawColor(200);
  doc.line(20, 68, pageWidth - 20, 68);

  doc.setFont('helvetica', 'bold');
  doc.text('Patient Info', 20, 80);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${data.patient_info?.name || 'N/A'}`, 25, 87);
  doc.text(`Age/Gender: ${data.patient_info?.age || 'N/A'} / ${data.patient_info?.gender || 'N/A'}`, 25, 94);

  doc.setFont('helvetica', 'bold');
  doc.text('Doctor Info', 110, 80);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${data.doctor_info?.name || 'N/A'}`, 115, 87);
  doc.text(`Hospital: ${data.doctor_info?.hospital || 'N/A'}`, 115, 94);

  addFooter();

  // Page 2: Medications
  doc.addPage();
  addHeader(2);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text('Medications', 20, 55);

  let y = 70;
  data.medications?.forEach((med, i) => {
    if (y > pageHeight - 40) {
      doc.addPage();
      addHeader(doc.internal.getNumberOfPages());
      y = 55;
    }
    doc.setFont('helvetica', 'bold');
    doc.text(`${i + 1}. ${med.name}`, 20, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Dosage: ${med.dosage} | Frequency: ${med.frequency} | Duration: ${med.duration}`, 25, y + 5);
    doc.text(`Purpose: ${med.purpose}`, 25, y + 10);
    y += 20;
  });

  addFooter();

  // Page 3: Interactions
  doc.addPage();
  addHeader(3);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text('Drug Interactions & Summary', 20, 55);

  doc.setFontSize(10);
  doc.text('AI Analysis Summary:', 20, 70);
  doc.setFont('helvetica', 'italic');
  const splitSummary = doc.splitTextToSize(data.plain_language_summary, pageWidth - 40);
  doc.text(splitSummary, 20, 77);

  y = 77 + (splitSummary.length * 5) + 15;
  doc.setFont('helvetica', 'bold');
  doc.text('Warnings:', 20, y);
  doc.setFont('helvetica', 'normal');
  data.drug_interactions?.forEach((int, i) => {
    doc.text(`• [${int.severity.toUpperCase()}] ${int.drugs.join(' + ')}: ${int.description}`, 25, y + 7 + (i * 10));
  });

  addFooter();

  doc.save(`MediLens_Report_${data.patient_info?.name || 'User'}.pdf`);
};
