import jsPDF from 'jspdf';

export const generateMedicinePDF = (data, query) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const addHeader = (pageNum) => {
    doc.setFillColor(10, 14, 26);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(0, 212, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text('MediLens AI', 20, 25);
    doc.setFontSize(10);
    doc.text('Medicine Comparison & Insights', 20, 32);
    
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${pageNum}`, pageWidth - 30, 25);
    
    doc.setDrawColor(255, 255, 255, 0.1);
    doc.line(0, 40, pageWidth, 40);
  };

  const addFooter = () => {
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by MediLens AI | For informational purposes only | Consult your doctor', pageWidth / 2, pageHeight - 10, { align: 'center' });
  };

  addHeader(1);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text(`Medical Comparison Report: ${query}`, 20, 55);
  doc.setFontSize(10);
  doc.text(`Date: ${new Date().toLocaleString()}`, 20, 62);

  doc.setDrawColor(200);
  doc.line(20, 68, pageWidth - 20, 68);

  let y = 80;
  data.medicines?.forEach((med, i) => {
    if (y > pageHeight - 60) {
      addFooter();
      doc.addPage();
      addHeader(doc.internal.getNumberOfPages());
      y = 55;
    }

    doc.setFillColor(245, 247, 250);
    doc.rect(20, y - 5, pageWidth - 40, 50, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(0, 212, 255);
    doc.text(med.name, 25, y + 5);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`${med.generic_name} | ${med.category}`, 25, y + 12);

    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text('Common Uses:', 25, y + 22);
    doc.setFont('helvetica', 'normal');
    doc.text(med.common_uses.join(', '), 25, y + 27, { maxWidth: pageWidth - 50 });

    doc.setFont('helvetica', 'bold');
    doc.text('Warnings:', 25, y + 37);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(239, 68, 68);
    doc.text(med.warnings.join(', '), 25, y + 42, { maxWidth: pageWidth - 50 });

    y += 60;
  });

  addFooter();
  doc.save(`MediLens_Medicine_Report_${query}.pdf`);
};
